<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Default Reqion
    |--------------------------------------------------------------------------
    |
    */

    1 => 'Abşeron',
    2 => 'Ağstafa',
    3 => 'Ağcabədi',
    4 => 'Ağdam',
    5 => 'Ağdaş',
    6 => 'Ağsu',
    7 => 'Astara',
    9 => 'Bakı',
    10 => 'Babək',
    11 => 'Balakən',
    12 => 'Bərdə',
    13 => 'Beyləqan',
    14 => 'Biləsuvar',
    15 => 'Cəbrayıl',
    16 => 'Cəlilabad',
    17 => 'Culfa',
    18 => 'Daşkəsən',
    19 => 'Füzuli',
    20 => 'Gəncə',
    21 => 'Gədəbəy',
    22 => 'Goranboy',
    23 => 'Göyçay',
    24 => 'Xanlar',
    25 => 'Hajigabul',
    26 => 'İmişli',
    27 => 'İsmayıllı',
    28 => 'Kəlbəcər',
    29 => 'Kangarli',
    30 => 'Kürdəmir',
    31 => 'Lankaran City',
    32 => 'Lachin',
    33 => 'Lankaran',
    34 => 'Lerik',
    35 => 'Masallı',
    36 => 'Mingəçevir',
    37 => 'Naftalan',
    38 => 'Neftçala',
    39 => 'Naxçıvan',
    40 => 'Oğuz',
    41 => 'Ordubad',
    42 => 'Qəbələ',
    43 => 'Qax',
    44 => 'Qazax',
    45 => 'Quba',
    46 => 'Qubadli',
    47 => 'Qobustan',
    48 => 'Qusar',
    49 => 'Şəki',
    50 => 'Sabirabad',
    51 => 'Sədərək',
    52 => 'Şahbuz',
    53 => 'Şəki',
    54 => 'Salyan',
    55 => 'Şərur',
    56 => 'Saatlı',
    57 => 'Dəvəçi',
    58 => 'Siyəzən',
    59 => 'Şəmkir',
    60 => 'Sumqayıt',
    61 => 'Şamaxı',
    62 => 'Samux',
    63 => 'Shirvan',
    64 => 'Şuşa',
    65 => 'Tərtər',
    66 => 'Tovuz',
    67 => 'Ucar',
    68 => 'Stepanakert',
    69 => 'Xaçmaz',
    70 => 'Xocalı',
    71 => 'Xizı',
    72 => 'Xocavənd',
    73 => 'Yardımlı',
    74 => 'Yevlakh',
    75 => 'Yevlakh Rayon',
    76 => 'Zəngilan',
    77 => 'Zaqatala',
    78 => 'Zərdab'
];
